name: Scala CI

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
      - name: Check sources formatting
        run: sbt scalafmtCheck
      - name: Check sbt and project dir formatting
        run: sbt scalafmtSbtCheck
      - name: Run tests
        run: sbt test
      - name: Build docs
        run: sbt docs/mdoc
  auto-approve:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'scala-steward'
        with:
          github-token: "${{ secrets.SCALA_STEWARD_MERGE_TOKEN }}"
